name: Release

on:
  push:
    tags:
      - "*"

jobs:
  api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          yarn --frozen-lockfile
          yarn global add turbo@1.5.5

      - name: Test
        run: turbo run test --scope=api

      - name: Docker login
        run: docker login -u bitmetro -p ${{ secrets.DOCKER_PASSWORD }} docker.io

      - name: Build and push api
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile.api
          tags: bitmetro/charter-api:${{ github.ref_name }}
          build-args: |
            SCOPE=api
  web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          yarn --frozen-lockfile
          yarn global add turbo@1.5.5

      - name: Test
        run: turbo run test --scope=web

      - name: Docker login
        run: docker login -u bitmetro -p ${{ secrets.DOCKER_PASSWORD }} docker.io

      - name: Build and push web app
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile.web
          tags: bitmetro/charter-web:${{ github.ref_name }}
          build-args: |
            SCOPE=web

  manager:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          yarn --frozen-lockfile
          yarn global add turbo@1.5.5

      - name: Test
        run: turbo run test --scope=manager

      - name: Docker login
        run: docker login -u bitmetro -p ${{ secrets.DOCKER_PASSWORD }} docker.io

      - name: Build and push manager app
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile.manager
          tags: bitmetro/charter-manager:${{ github.ref_name }}
          build-args: |
            SCOPE=manager