name: Release

on:
  push:
    tags:
      - "*"

jobs:
  api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          yarn --frozen-lockfile
          yarn global add turbo@1.5.5

      - name: Test
        run: turbo run test --scope=api

      - name: Docker login
        run: docker login -u bitmetro -p ${{ secrets.DOCKER_PASSWORD }} docker.io

      - name: Build and push api
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile.api
          tags: bitmetro/booking-api:${{ github.ref_name }}
          build-args: |
            SCOPE=api
            PORT=3001
  web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          yarn --frozen-lockfile
          yarn global add turbo@1.5.5

      - name: Test
        run: turbo run test --scope=web

      - name: Docker login
        run: docker login -u bitmetro -p ${{ secrets.DOCKER_PASSWORD }} docker.io

      - name: Build and push web app
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile.web
          tags: bitmetro/booking-web:${{ github.ref_name }}
          build-args: |
            SCOPE=web
            PORT=3000
            NEXT_PUBLIC_APP_URL: https://booking.bitmetro.io
            NEXT_PUBLIC_API_URL: https://booking-api.bitmetro.io
            NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51MXHdEFwhEz4kIqD7ZyQo6HcYhFY03byVW2SHpQOglZBDhTeZ0jkqknptPK63R2kc8BMRlXP534sw7femKMV05PE00SbVdp8jA
